name: Deploy my Static Page

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Lua 5.1
      uses: leafo/gh-actions-lua@v10
      with:
        lua-version: 'luajit'

    - name: Run Lua script to generate HTML and CSS
      run: luajit src/gen.lua

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
