name: generate-static-page-lua

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up LuaJit
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "luajit-openresty"

    - name: Run Lua script to generate HTML and CSS
      run: luajit src/gen.lua

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
